name: Build first Java project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository code
        uses: actions/checkout@v2
      - name: Build
        run: make install
      - name: Run the app
	run: make run-dist
